print("\n\t.____    .__\n\t|    |   |__| _____   ____\n\t|    |   |  |/     \\_/ __ \\\n\t|    |___|  |  Y Y  \\  ___/\n\t|_______ \\__|__|_|  /\\___  >\n\t        \\/        \\/     \\/\n\t\n\t    EWAN BREAKEY. MADE IN MSHINE.\n\t\n    #############################################\n")
print("Lime Version " .. require('engine.version'))
print("LOVE2D " .. string.format("Version %d.%d.%d - %s", love.getVersion()))
print("LoveBird web console hosted on 127.0.0.1:8000")
print("\n\n")
require('engine.require')
require('engine.events')
require('engine.packages')
return LoadPackage('main', true)
